
name: Deploy to nuget.org

on: 
  workflow_dispatch:

jobs:
  release:

    runs-on: windows-2019

    steps:

    - uses: actions/checkout@v2
      with:
        fetch-depth: 0    
        
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
        
    - run: npm install
    - run: npm run build
    
    - uses: nuget/setup-nuget@v1
    - run: nuget pack PxWebScbStyle.nuspec
    
    - name: Depoly to Nuget
      run: |
           $package = Get-ChildItem -Recurse -Filter *.nupkg
           nuget push $package $env:nuget_api_key -src https://nuget.org
      env:
        nuget_api_key: ${{ secrets.NUGET_API_KEY }}
